# Generated by Django 3.0.7 on 2020-08-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
